### ISSUE TITLE
the sql file has password

### ISSUE THREAD

**Issue by chr1s78** [alexanderthegreat96/dth-division2-api#1]
hi, i want to use the sql file for my iOS app, but the sql file has password, can u tell me the password? thx

**Comment by alexanderthegreat96** [comment]
What password are you talking about?

**Comment by alexanderthegreat96** [comment]
user: alexander
Pass: JaRyk3ys4fVZrwHzMAba

These are the credentials you can use to send requests to the API.

**Comment by alexanderthegreat96** [comment]
do me a favour and do a git pull. use docker to deploy it. takes 2 minutes and you will have no issues.

**Comment by alexanderthegreat96** [comment]
You may download the latest release. The old one had some bugs. I didn't know people would be interested in this so I stopped updating it.
